name: .NET Core Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101

    - name: Build 'Chakra.Core'
      run: |
        cd Chakra.Core
        dotnet build --configuration Release

    - name: Build 'Chakra.Core.AspnetCore'
      run: |
        cd Chakra.Core.AspnetCore
        dotnet build --configuration Release

    - name: Build 'Chakra.Core.Configurations'
      run: |
        cd Chakra.Core.Configurations
        dotnet build --configuration Release

    - name: Build 'Chakra.Core.EntityFramework'
      run: |
        cd Chakra.Core.EntityFramework
        dotnet build --configuration Release

    - name: Build 'Chakra.Core.EntityFramework.Tests'
      run: |
        cd Chakra.Core.EntityFramework.Tests
        dotnet build --configuration Release

    - name: Build 'Chakra.Core.Mocks'
      run: |
        cd Chakra.Core.Mocks
        dotnet build --configuration Release

    - name: Build 'Chakra.Core.Mocks.Tests'
      run: |
        cd Chakra.Core.Mocks.Tests
        dotnet build --configuration Release

    - name: Build 'Chakra.Core.MongoDb'
      run: |
        cd Chakra.Core.MongoDb
        dotnet build --configuration Release

    - name: Build 'Chakra.Core.Tests'
      run: |
        cd Chakra.Core.Tests
        dotnet build --configuration Release

    - name: Build 'Chakra.Core.WebApi'
      run: |
        cd Chakra.Core.WebApi
        dotnet build --configuration Release

    - name: Build 'Chakra.Core.Windows'
      run: |
        cd Chakra.Core.Windows
        dotnet build --configuration Release